### ISSUE TITLE
Переключение кодировок по F8

### ISSUE THREAD

**Issue by DM-VLK** [shmuz/far2l#16]
Заметил что F8 в редакторе (и в родителе тоже) переключает между кодировками 1252/437, а не 1251/866 как в Windows версии FAR. Возможно ли сделать поведение аналогично Windows версии или так сделано специально?

**Comment by DM-VLK** [comment]
Ради интереса переключил язык/локаль системы на русские и поведение стало таким как нужно, но например Windows у меня английская, форматы Russian(Ukraine) и язык FAR’a английский, а кодировки по F8 какие и нужно. Можно ли как-то настроить это поведение?

**Comment by shmuz** [comment]
Не вникал в этот вопрос, у меня 1251/866 (как это получилось уже не помню.
Редактор настроен на UTF-8 для новых файлов, так что если пишу на русском, то это всегда UTF-8.

**Comment by DM-VLK** [comment]
Вышло починить. Запуск **LC_ALL=ru_RU.UTF-8 far2l** ожидаемо дал нужное поведение, а потом я поискал в исходниках и нашел нужное место. 

В файле APIStringCodepages.cpp заменил 221-ю строку на
    
const char *lc = setlocale(LC_NUMERIC, NULL);

Выбрал LC_NUMERIC, вроде вполне разумно.

После 338 вставил

if (IsLocaleMatches(lc, "ru_UA")) { return Codepages{866, 1251}; }

А можно добавить условие, что если локаль начинаеться с ru_ ставить страницы 866/1251

**Comment by shmuz** [comment]
Мне бы не хотелось иметь в исходниках жёстко-закодированные правила. Лучше такое выносить в конфигурацию.
Но это я так, в общем, не разбираясь в проблеме (у меня-то такой проблемы почему-то нет).
Пусть данный тикет побудет открытым, ыозможно со временем поймём, что надо (или не надо) делать.

**Comment by shmuz** [comment]
> В файле APIStringCodepages.cpp заменил 221-ю строку на
const char *lc = setlocale(LC_NUMERIC, NULL);
Выбрал LC_NUMERIC, вроде вполне разумно.

Когда 2-й параметр==NULL, изменений в текущей локали не делается, это может только повлиять на возвращаемое значение (https://cplusplus.com/reference/clocale/setlocale/). Поэтому смысла в данном изменении нет.

> if (IsLocaleMatches(lc, "ru_UA")) { return Codepages{866, 1251}; }

Это можно добавить.

> А можно добавить условие, что если локаль начинаеться с ru_ ставить страницы 866/1251

Технически добавить легко, но не хотелось бы умножать в программе куски, заточенные на определённый (в данном случае, русский) язык.

**Comment by DM-VLK** [comment]
> > В файле APIStringCodepages.cpp заменил 221-ю строку на
> > const char *lc = setlocale(LC_NUMERIC, NULL);
> > Выбрал LC_NUMERIC, вроде вполне разумно.
> 
> Когда 2-й параметр==NULL, изменений в текущей локали не делается, это может только повлиять на возвращаемое значение (https://cplusplus.com/reference/clocale/setlocale/). Поэтому смысла в данном изменении нет.

Увы, но так не сработает (я собрал новую версию). Вот если бы в каждой строке команды locale у меня было ru_UA.UTF-8, то это бы сработало, но так по прежнему проверяется LC_CTYPE которая будет иметь значение en_US. Именно и нужно чтобы в переменной lc было значение LC_NUMERIC. Тем у кого язык и форматы одинаковы вообще не важно какую из переменных locale проверять, а вот в таком случае как у меня появляется разница.

**Comment by DM-VLK** [comment]
> Решение оказалось уже предусмотренным

Спасибо. Стоит добавить в справку/FAQ

**Comment by shmuz** [comment]
> Стоит добавить в справку/FAQ

- Pull request не был бы лишним :)
Если возьмётесь, то модифицироваться должны файлы FarUkr.hlf.m4 FarRus.hlf.m4 FarEng.hlf.m4
- Или создать для этого новый Issue, чтобы не забылось
