### ISSUE TITLE
Aborted (core dumped) после завершения

### ISSUE THREAD

**Issue by DM-VLK** [shmuz/far2l#19]
Иногда после завершения в терминале вижу **"Aborted (core dumped)"**. Думаю это не очень хорошо.

**Comment by shmuz** [comment]
Наблюдаю уже давно, но зацепиться пока не получается, даже с дебаггером.

**Comment by shmuz** [comment]
Сейчас сделал коммит, который (возможно) лечит эту проблему.
Хотелось бы узнать, пропали падения на вашей системе, или нет.

**Comment by DM-VLK** [comment]
Обновился, позапускал около десятка раз выполняя разные операции и кажется этого сообщения/явления больше нет.

P.S. Правда появился другой вопрос со сборкой, но я уезжаю до вечера понедельника т.ч. потом спрошу.

**Comment by shmuz** [comment]
Закрываю, т.к. эти падения вроде прекратились.
Если возобновятся, можно переоткрыть.
