### ISSUE TITLE
cmake version and TRANSFORM subcommand

### ISSUE THREAD

**Issue by sorcodiv** [shmuz/far2l#21]
Hello!

В требованиях указана версия cmake ( >= 3.2.2 ).
В Ubuntu 16.04 cmake version 3.5.1.
При компиляции возникает ошибка:
CMake Error at luamacro/CMakeLists.txt:27 (list): list does not recognize sub-command TRANSFORM
Причина - для TRANSFORM требуется cmake не ниже 3.12 https://cmake.org/cmake/help/latest/command/list.html#transform.
Все остальные бинарники собираются в Ubuntu 16.04.
Можно ли в luamacro обойтись без TRANSFORM?

И второй вопрос, так же связанный с компиляцией в Ubuntu 16.04.
В CMakeLists.txt прописана зависимость от luajit-2.1. Можно ли использовать luajit-2.0, или эта версия не совместима с luafar?

In required dependencies cmake version specified >= 3.2.2.
When I compile far2l with lua support in Ubuntu 16.04 (cmake version 3.5.1), I get an error:
CMake Error at luamacro/CMakeLists.txt:27 (list): list does not recognize sub-command TRANSFORM
Because TRANSFORM is new in cmake since 3.12 https://cmake.org/cmake/help/latest/command/list.html#transform.
All other binaries build fine in Ubuntu 16.04.
Is it possible not to use "TRANSFORM" in luamacro?

And one more question, may I use luajit-2.0 instead of luajit-2.1 with luafar?

**Comment by shmuz** [comment]
TRANSFORM убрал, проверьте как стало теперь

luajit-2.0 так же как и lua5.1 должны работать.
Более подробно:
luafar пытается загрузить `libluajit-5.1.so` и `liblua5.1.so` (если 1-ю не получится то 2-ю).
Я не знаю, какое имя у длл-ки luajit-2.0, если такое же, то должно работать, если другое - могу добавить в список.
